// Elementos do DOM
export const elements = {
  btnCreate: document.getElementById("btnCreate"),
  createMenu: document.getElementById("createMenu"),
  addBoardBtn: document.getElementById("addBoardBtn"),
  addCardBtn: document.getElementById("addCardBtn"),
  boardsList: document.getElementById("boardsList"),
  boardTitle: document.getElementById("boardTitle"),
  boardContent: document.getElementById("boardContent"),
  modal: document.getElementById("modal"),
  modalContent: document.getElementById("modalContent"),
  btnCloseModal: document.getElementById("btnCloseModal"),
  btnDelete: document.getElementById("btnDelete"),
  btnArchive: document.getElementById("btnArchive"),
  btnMaximize: document.getElementById("btnMaximize"),
  btnRestore: document.getElementById("btnRestore"),
  userAvatar: document.getElementById("userAvatar"),
  userSettingsMenu: document.getElementById("userSettingsMenu"),
  settingExpandBoard: document.getElementById("expandBoardCheckbox"),
  btnSettings: document.getElementById("btnSettings"),
  settingsMenu: document.getElementById("settingsMenu"),
  settingExpandBoardSidebar: document.getElementById("settingExpandBoard"),
  sidebar: document.getElementById("sidebar"),
  sidebarToggleBtn: document.getElementById("sidebarToggleBtn"),
  modalPlanilhaEdicaoAvancada: document.getElementById("modalPlanilhaEdicaoAvancada"),
  btnCloseModalPlanilhaAvancada: document.getElementById("btnCloseModalPlanilhaAvancada"),
  formPlanilhaAvancada: document.getElementById("formPlanilhaAvancada"),
  btnAdicionarColunaPlanilhaAvancada: document.getElementById("btnAdicionarColunaPlanilhaAvancada"),
  btnAdicionarLinhaPlanilhaAvancada: document.getElementById("btnAdicionarLinhaPlanilhaAvancada"),
  btnRemoverLinhasSelecionadasPlanilhaAvancada: document.getElementById("btnRemoverLinhasSelecionadasPlanilhaAvancada"),
  btnExcluirPlanilhaAvancada: document.getElementById("btnExcluirPlanilhaAvancada"),
  btnArquivarPlanilhaAvancada: document.getElementById("btnArquivarPlanilhaAvancada"),
  btnCancelarPlanilhaAvancada: document.getElementById("btnCancelarPlanilhaAvancada"),
  btnSalvarPlanilhaAvancada: document.getElementById("btnSalvarPlanilhaAvancada"),
  theadColunasAvancada: document.getElementById("theadColunasAvancada"),
  tbodyLinhasAvancada: document.getElementById("tbodyLinhasAvancada")
};
